sudo: required
services: 
  - docker

before_install:
  - docker build -t nkowsik86/docker-react -f Dockerfile.dev .

script:
  - docker run nkowsik86/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2" # region
  app: "docker-react" #Application
  env: "DockerReact-env" #Environment under application
  bucket_name: "elasticbeanstalk-us-east-2-231440092033" # s3 Bucket
  bucket_path: "docker-react"   #Application Name for the first name other Bucket in S3
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"