sudo: required
services: 
  - docker

before_install:
  - gem install bundler
  - docker build -t nkowsik86/docker-react -f Dockerfile.dev .

scritps:
  - docker run nkowsik86/docker-react npm run test -- --coverage
