sudo: required
services: 
  - docker

before_install:
  - gem install bundler
  - gem install rake
  - docker build -t nkowsik86/docker-react -f Dockerfile.dev .

scripts:
  - docker run nkowsik86/docker-react npm run test -- --coverage
